name: covid-predict
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - pip
  - pip:
      - tensorflow
      - streamlit
      - boto3
      - dotenv
